### ISSUE TITLE
How to make FASTA file from paired end FASTQ?

### ISSUE THREAD

**Issue by sdwfrost** [raunaq-m/MLEHaplo#2]
In the step

```
 perl construct_graph.pl "fastafile" "kmerfile" "threshold" "graphfile" "s"
```

One has to make a single FASTA file from paired end FASTQ. It appears that you have to run

```
perl fastqtofasta.pl <read file>
```

for each read, and then cat...is this OK (given that the reverse read is in the opposite direction)

**Comment by raunaq-m** [comment]
Yes. One can use cat to combine the two fasta files. The graph stores both forward and reverse kmers from every read, so the reverse orientation is taken care of.

**Comment by raunaq-m** [comment]
Additionally, I have uploaded a script to compute the graph file in a much faster way. Suppose you want to generate a graph for kmer size = k. 
1. Perform kmer counting using a k-mer counting software (dsk) for k+1 : "kmer_1file"
2. Use kmer counts computed for size k computed earlier : "kmerfile"

Use the script : construct_graph_kmer.pl as follows:
perl construct_graph_kmer.pl -k1 "kmer_1file" -k "kmerfile" -t "threshold" -w "graphoutputfile" 

This is extremely fast as (k+1)-mer counting can be done efficiently, rather than going through the reads again.

**Comment by raunaq-m** [comment]
This update will also avoid your conversion of fastq file to fasta, as kmer counting tools are flexible with usage of fastq/fasta/gzipped files. I'm working on the code here and will introduce more flexibility in the code soon. 
Apologies for delay earlier, and thank you for your patience!
